### ISSUE TITLE
Simple Dunno : libgbaio

### ISSUE THREAD

**Issue by inukaze** [TricksterGuy/cs2110-vbam#2]
Hi there, i want know if libgbaio is OpenSource or FreeSoftware. and case the answer be negative. you can tell me if exist an FreeSoftware alternative vesion of libgbaio ?

**Comment by TricksterGuy** [comment]
Hmm are you a georgia tech student?

Nonetheless, this repo is pretty old and I wouldn't suggest it be used for anything.

I would suggest you use the latest version of [visualboyadvance-m](https://github.com/visualboyadvance-m/visualboyadvance-m)

But if you are interested. That file contains a hacked version of printf (and the functions needed to support it). This forked version of vbam here contains a backdoor to get said use of printf in the emulated code to work. It was a rather clunky, sneaky solution.

HOWEVER

I realize that VBA-M has such functionality already within it via an assembly code hack you insert in your code.

```
.arm
.global vbaprint
.type   vbaprint STT_FUNC
.text
vbaprint:
    swi 0xFF0000        @!!!!!!! Doesn't work on hardware !!!!!!!
    bx lr
```

Add a function prototype for it

```
void vbaprint(const char *message);
```

And call.

I'm working on a cleaner solution for use in the course.

**Comment by inukaze** [comment]
> Hmm are you a georgia tech student?
not, i am from venezuela.

**Comment by TricksterGuy** [comment]
This repo shouldn't be of any interest to you then. As stated just use the official version of [visualboyadvance-m](https://github.com/visualboyadvance-m/visualboyadvance-m)
